author:
  name             : "Jongyun Jung (John)"
  avatar           : "/images/OSU_2022.jpeg"
  bio              : "PhD Candidate in Biomedical Informatics at The Ohio State University. My work focuses on longitudinal modeling, genetics, and precision fracture prediction."
  location         : "Columbus, Ohio, USA"
  email            : "jung.731@osu.edu"
  github           : "jystatistics"
  linkedin         : "jongyunjung"
  googlescholar    : "https://scholar.google.com/citations?user=IxZPqEkAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0002-9258-5397"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-GTYJE767PZ"
